# Generated by Django 5.2.6 on 2026-02-26 15:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(default='kg', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Produce Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('godown', 'Godown Operator'), ('transporter', 'Transporter'), ('consumer', 'Consumer / Family'), ('admin', 'Admin')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_location', models.CharField(max_length=300)),
                ('farm_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('crops_grown', models.TextField(help_text='Comma-separated list of crops')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('capacity_tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'godown'}, on_delete=django.db.models.deletion.CASCADE, related_name='godowns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg_paid', models.DecimalField(decimal_places=2, help_text='Price godown pays farmer per kg', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], default='B', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Inspection'), ('accepted', 'Accepted into Stock'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_deliveries', to='essoko.godown')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essoko.producecategory')),
            ],
        ),
        migrations.CreateModel(
            name='StockListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_available_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_kg', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], default='B', max_length=5)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('best_before', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produce/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('paused', 'Paused')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essoko.producecategory')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='essoko.godown')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='Locked at time of order', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pickup_method', models.CharField(choices=[('self_pickup', 'Self Pickup'), ('transporter', 'Transporter')], default='self_pickup', max_length=20)),
                ('delivery_address', models.TextField(blank=True, help_text='If transporter delivery')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed by Godown'), ('ready', 'Ready for Pickup'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(limit_choices_to={'role': 'consumer'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='essoko.godown')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='essoko.stocklisting')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=300)),
                ('delivery_location', models.CharField(max_length=300)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open for Bids'), ('assigned', 'Transporter Assigned'), ('picked_up', 'Picked Up from Godown'), ('delivered', 'Delivered to Consumer'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_job', to='essoko.order')),
                ('transporter', models.ForeignKey(blank=True, limit_choices_to={'role': 'transporter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
